---
- name: My playbook
  hosts: all
  remote_user: ec2-user
  tasks:
     - name: Leaving a mark
       command: "touch /tmp/ansible_was_here"

     - name: Leaving a second mark
       command: "touch /tmp/ansible_was_here2"